wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1655720582
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 13
      - 16
      4: 3.9.12
      5: 0.12.18
      8:
      - 3
      - 5
config_model:
  desc: null
  value:
    dropout_rate: 0.2
    l_units:
    - 30
    - 30
    learning_rate:
      lr_max: 1.0e-05
      lr_middle: 1.0e-07
      lr_min: 1.0e-09
      scheduler: 0
      step_middle: 1300
      step_min: 3000
    noise: 0
    optimizer: Adam
    save_path: ''
config_training:
  desc: null
  value:
    batch_size: 8192
    display_step: 1
    epochs_max: 1
    n_trains: 1
    patience: 100
    tol: 1.0e-06
    val_size: 8192
over_folder_dir:
  desc: null
  value: Neural_Networks/Tensorflow/Problem_1/NN_saves
remark:
  desc: null
  value: ''
trial_id:
  desc: null
  value: 0
